stages:
  data_ingestion:
    cmd: C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\src\data_ingetion.py
    deps:
    - C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\src\data_ingetion.py
    params:
    - data_ingestion.test_size
    outs:
    - data\raw
  data_preprocessing:
    cmd: python C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\src\data_preprocessing.py
    deps:
    - C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\data\raw
    - C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\src\data_preprocessing.py
    outs:
    - data\interim
  feature_engineering:
    cmd: python C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\src\feature_engineering.py
    deps:
    - C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\data\interim
    - python C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\src\feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data\processed
  model_building:
    cmd: python C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\src\model_building.py
    deps:
    - C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\data\processed
    - C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\src\model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models\model.pkl
  model_evaluation:
    cmd: python C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\src\model_evaluation.py
    deps:
    - C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\models\model.pkl
    - C:\Users\Mahendra\Favorites\mlops-02\MLOPS-complete-pipeline\src\model_evaluation.py
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step